name: prebuild

on:
  workflow_dispatch:

env:
  GLIBC_VERSION: 2.3.2

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download glibc
        run: |
          wget -q https://github.com/fcitx-contrib/m17n-cmake/releases/download/glibc-${{ env.GLIBC_VERSION }}/glibc-${{ env.GLIBC_VERSION }}.tar.gz
          tar xf glibc-${{ env.GLIBC_VERSION }}.tar.gz -C m17n-db glibc-${{ env.GLIBC_VERSION }}/localedata/charmaps

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y autopoint gettext

      - name: Build data
        working-directory: m17n-db
        run: |
          ./bootstrap.sh
          ./configure --with-charmaps=glibc-${{ env.GLIBC_VERSION }}/localedata/charmaps --prefix=/usr
          make
          DESTDIR=dist make install
          cd dist/usr && tar cj \
            --sort=name --mtime=@0 \
            --numeric-owner --owner=0 --group=0 --mode=go+u,go-w \
            -f ../../../m17n-db.tar.bz2 share/m17n

      - name: Release data
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            m17n-db.tar.bz2

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
